# `todo-app-whisker` — a Whisker app.

[workspace]
members = ["."]
resolver = "2"

[package]
name = "todo-app-whisker"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
whisker = "0.10.1"
whisker-input = "0.10.1"
whisker-local-store = "0.10.1"
whisker-safe-area = "0.10.1"
